/* ==========================================================================
   Deutsch → Englisch für die Wochenkarte
   --------------------------------------------------------------------------
   Grundlage ist die komplette Speisekarte von Da Mimmo (Stand 2025):
   Antipasti, Salate, Suppen, Pasta, Pizza, Burger, Fleisch, Fisch.
   Italienische Gerichtnamen bleiben stehen — übersetzt wird die deutsche
   Beschreibung darunter.

   Reihenfolge: zuerst ganze Sätze (SAETZE), dann lange Wortgruppen, dann
   einzelne Begriffe. Was die App vorschlägt, lässt sich im Feld „English“
   jederzeit überschreiben; diese Korrektur gilt dann immer.
   ========================================================================== */
const Woerterbuch = (()=>{

/* Ganze Beschreibungen, die so auf der Karte stehen ----------------------- */
const SAETZE = {
  'frisch, saisonal und jede woche neu für sie zusammengestellt': 'fresh, seasonal and put together anew every week, just for you',
  'werfen sie gerne einen blick auf unsere dessertkarte für süße highlights': 'feel free to take a look at our dessert menu for sweet highlights',
  'werfen sie gerne einen blick auf unsere dessertkarte': 'feel free to take a look at our dessert menu',
  'guten appetit': 'enjoy your meal',
  'wir wünschen ihnen einen guten appetit': 'we wish you a pleasant meal',
  'fragen zu allergien und unverträglichkeiten? sprechen sie uns gerne an': 'questions about allergies or intolerances? please ask our staff',
  'gemischte vorspeisen aus der vitrine': 'mixed starters from our counter',
  'preis nach menge': 'price by portion',
  'kleinere portionen auf anfrage erhältlich': 'smaller portions available on request',
  'keine kleinen portionen': 'no small portions',
  'an feiertagen gilt die wochenkarte nicht': 'not valid on public holidays',
  'außer-haus-verkauf & lieferung': 'takeaway & delivery',
  'dienstag bis samstag': 'Tuesday to Saturday',
  'montag bis freitag': 'Monday to Friday',
  'montag bis samstag': 'Monday to Saturday',
  'extra karte': 'Specials',
  'extrakarte': 'Specials',
  'wochenkarte': 'Weekly Menu',
  'mittagstisch': 'Lunch Menu',
  'speisen': 'Food',
  'empfohlene getränke': 'Recommended drinks',
  'getränke': 'Drinks',
  'aperitivo': 'Aperitivo',
  'aperitif': 'Aperitif',
  'vorspeisen': 'Starters',
  'hauptgerichte': 'Main courses',
  'hauptspeisen': 'Main courses',
  'nachspeisen': 'Desserts',
  'nachtisch': 'Dessert',
  'desserts': 'Desserts',
  'beilagen': 'Side dishes',
  'salate': 'Salads',
  'suppen': 'Soups',
  'weine': 'Wines',
  'offene weine': 'Wines by the glass',
  'fisch': 'Fish',
  'fleisch': 'Meat',
  'für kinder': 'For children',
  'kinderkarte': 'For children',
  'tisch reservieren': 'Reserve a table',
  'wichtige hinweise': 'Please note',
};

/* Wortgruppen und Begriffe — lange zuerst, das ordnet die App selbst ------ */
const BEGRIFFE = {
  /* --- Beilagen und Hinweise, die überall auftauchen --- */
  'dazu servieren wir ihnen eine beilage': 'served with a side dish',
  'dazu erhalten sie eine beilage': 'served with a side dish',
  'dazu eine beilage': 'with a side dish',
  'serviert mit einer beilage': 'served with a side dish',
  'dazu salatbeilage': 'with a side salad',
  'dazu salat': 'with a side salad',
  'zusätzliche beilage': 'extra side dish',
  'salatbeilage': 'side salad',
  'gemüsebeilage': 'side of vegetables',
  'beilage': 'side dish',
  'nicht als kleine portion erhältlich': 'not available as a small portion',
  'auf wunsch zusätzlich mit': 'add if you like',

  /* --- Antipasti --- */
  'parmaschinken mit melone': 'Parma ham with melon',
  'tomaten mit mozzarella und frischem basilikum': 'tomatoes with mozzarella and fresh basil',
  'rinderfilet dünngeschnitten': 'thinly sliced beef fillet',
  'gehobeltem parmesan': 'shaved parmesan',
  'parmesanhobel': 'shaved parmesan',
  'parmesankäse': 'parmesan',
  'tomatenconcassee': 'tomato concassée',
  'tomatenconcassée': 'tomato concassée',
  'gerösteten brotscheiben': 'toasted bread',
  'kalte kalbsbratenscheibchen': 'thin slices of cold roast veal',
  'hausgemachter thunfischsoße': 'homemade tuna sauce',
  'shrimps-cocktail': 'shrimp cocktail',
  'parmaschinken': 'Parma ham',
  'melone': 'melon',
  'filatakäse': 'filata cheese',
  'kuhmilch': "cow's milk",

  /* --- Salate --- */
  'gemischter salat': 'mixed salad',
  'tomaten-gurkensalat': 'tomato and cucumber salad',
  'tomatensalat': 'tomato salad',
  'gurkensalat': 'cucumber salad',
  'artischockensalat': 'artichoke salad',
  'rucola-salat': 'rocket salad',
  'kräuter-sahnedressing': 'herb cream dressing',
  'balsamico-dressing': 'balsamic dressing',
  'olivenöl-balsamico': 'olive oil and balsamic',
  'pinienkernen': 'pine nuts',
  'pinienkerne': 'pine nuts',
  'dressing': 'dressing',

  /* --- Suppen --- */
  'kraftbrühe mit aufgeschlagenem ei': 'clear broth with whisked egg',
  'nach römischer art': 'Roman style',
  'tomatencremesuppe': 'cream of tomato soup',
  'gemüsesuppe': 'vegetable soup',
  'kraftbrühe': 'clear broth',
  'mit fleisch gefüllte ringnudeln': 'meat-filled tortellini',
  'fleischgefüllte ringnudeln': 'meat-filled tortellini',
  'ringnudeln': 'tortellini',

  /* --- Pasta --- */
  'gemischte nudeln': 'mixed pasta',
  'nudelrollen mit fleischfüllung': 'pasta rolls with a meat filling',
  'teigblätter': 'pasta sheets',
  'bandnudeln': 'tagliatelle',
  'kartoffelnudeln': 'gnocchi',
  'nudeln': 'pasta',
  'knoblauchscheiben': 'sliced garlic',
  'rinderhackfleisch': 'minced beef',
  'hackfleisch': 'minced meat',
  'fleischragout': 'meat ragù',
  'körnigem senf': 'wholegrain mustard',
  'körniger senf': 'wholegrain mustard',
  'pikanter käsesoße': 'spicy cheese sauce',
  'käsesoße': 'cheese sauce',
  'tomaten-sahnesoße': 'tomato and cream sauce',
  'brandy-sahne-tomatensoße': 'brandy, cream and tomato sauce',
  'leichter tomatensoße': 'light tomato sauce',
  'pikanter tomatensoße': 'spicy tomato sauce',
  'würzig-pikanter tomatensoße': 'spicy, aromatic tomato sauce',
  'tomatensoße': 'tomato sauce',
  'sahnesoße': 'cream sauce',
  'gorgonzolasoße': 'gorgonzola sauce',
  'weißweinsoße': 'white wine sauce',
  'sahne-safran-soße': 'saffron cream sauce',
  'safran-sahnesoße': 'saffron cream sauce',
  'safransoße': 'saffron sauce',
  'safran': 'saffron',
  'honigsoße': 'honey sauce',
  'zitronensoße': 'lemon sauce',
  'grüner soße': 'green sauce',
  'burgersoße': 'burger sauce',
  'fischsoße': 'fish sauce',
  'thunfischsoße': 'tuna sauce',
  'rosa pfeffer-sahnesoße': 'pink peppercorn cream sauce',
  'pfeffer-sahnesoße': 'peppercorn cream sauce',
  'mit knoblauch abgeschmeckt': 'seasoned with garlic',
  'al dente gekocht': 'cooked al dente',
  'geschichtet': 'layered',
  'überbacken': 'gratinated',
  'bechamel': 'béchamel',
  'mascarpone': 'mascarpone',
  'spinat': 'spinach',
  'erbsen': 'peas',
  'broccoli': 'broccoli',
  'brokkoli': 'broccoli',

  /* --- Pizza --- */
  'gefüllte pizza': 'folded pizza',
  'vegetarische pizza': 'vegetarian pizza',
  'diverse antipasti': 'assorted antipasti',
  'pilz der saison': 'mushroom of the season',
  'pilzen der saison': 'mushrooms of the season',
  'büffelmozzarella': 'buffalo mozzarella',
  'ziegenkäse': "goat's cheese",
  'schafskäse': 'feta',
  'gorgonzola-käse': 'gorgonzola',
  'trüffelöl': 'truffle oil',
  'trüffelmayonnaise': 'truffle mayonnaise',
  'trüffel-steinpilzcreme': 'truffle and porcini cream',
  'ananas': 'pineapple',
  'spargel': 'asparagus',
  'oliven': 'olives',
  'mais': 'sweetcorn',
  'glutenfrei': 'gluten-free',
  'maisstärke': 'corn starch',
  'reismehl': 'rice flour',
  'sauerteig': 'sourdough',
  'teig': 'dough',

  /* --- Burger --- */
  'karamellisierten zwiebeln': 'caramelised onions',
  'roten zwiebeln': 'red onions',
  'eisbergsalat': 'iceberg lettuce',
  'avocadocreme': 'avocado cream',
  'knoblauchcreme': 'garlic cream',
  'balsamicocreme': 'balsamic cream',
  'gin-mayonnaise': 'gin mayonnaise',
  'mayonnaise': 'mayonnaise',
  'paprikafilets': 'pepper strips',
  'tomatenscheiben': 'tomato slices',
  'preiselbeeren': 'cranberries',
  'gemüsepatty': 'veggie patty',
  'lachssteak': 'salmon steak',
  'brötchen': 'bun',
  'krosses': 'crisp',
  'rundes': 'round',
  'edamer': 'Edam',
  'camembert': 'camembert',
  'pommes frites': 'fries',
  'pommes': 'fries',
  'ketchup': 'ketchup',

  /* --- Fleisch --- */
  'paniertes schweinemedaillon': 'breaded pork medallion',
  'schweinemedaillons': 'pork medallions',
  'schweinemedaillon': 'pork medallion',
  'in scheiben geteiltes rumpsteak vom grill': 'sliced grilled rump steak',
  'zarte scheiben vom grill': 'tender slices from the grill',
  'auswahl verschiedener fleischsorten': 'selection of different meats',
  'liebevoll zubereitet auf dem grill': 'lovingly prepared on the grill',
  'eine hochwertige': 'a fine',
  'rindfleischstreifen': 'strips of beef',
  'rinderfiletstreifen': 'strips of beef fillet',
  'rinderfilet': 'beef fillet',
  'schweinefilet': 'pork fillet',
  'lammfilet': 'lamb fillet',
  'kalbsrücken': 'saddle of veal',
  'kalbfleisch': 'veal',
  'rumpsteak': 'rump steak',
  'angus rumpsteak': 'Angus rump steak',
  'hähnchenbrust': 'chicken breast',
  'hähnchenfleisch': 'chicken',
  'grünen pfeffer': 'green peppercorns',
  'grüner pfeffer': 'green peppercorns',
  'rosa pfeffer': 'pink peppercorns',
  'in feinem olivenöl gebraten': 'fried in fine olive oil',
  'in olivenöl gebraten': 'fried in olive oil',
  'gebratenen': 'fried',
  'gebratenem': 'fried',
  'gebratene': 'fried',
  'gebraten': 'fried',
  'gegrilltem': 'grilled',
  'gegrillt': 'grilled',
  'frittierter': 'deep-fried',
  'paniert': 'breaded',
  'verfeinert mit': 'refined with',
  'garstufe': 'cooking level',

  /* --- Fisch --- */
  'birnen-ingwer-chutney': 'pear and ginger chutney',
  'ingwer': 'ginger',
  'birne': 'pear',
  'fischfilet': 'fish fillet',
  'lachsfilet': 'salmon fillet',
  'hähnchenfilet': 'chicken fillet',
  'seelachs': 'pollock',
  'dorade': 'sea bream',
  'wolfsbarsch': 'sea bass',
  'meeresfrüchten': 'seafood',
  'meeresfrüchte': 'seafood',
  'flusskrebsen': 'crayfish',
  'tintenfisch': 'squid',
  'muscheln': 'mussels',
  'thunfisch': 'tuna',
  'gambas': 'king prawns',
  'gamba': 'king prawn',
  'shrimps': 'shrimps',
  'lachs': 'salmon',

  /* --- Gemüse, Kräuter, Zutaten --- */
  'frischen champignons': 'fresh mushrooms',
  'frische champignons': 'fresh mushrooms',
  'champignons': 'mushrooms',
  'pfifferlingen': 'chanterelles',
  'pfifferlinge': 'chanterelles',
  'steinpilze': 'porcini',
  'artischocken': 'artichokes',
  'auberginen': 'aubergines',
  'cherrytomaten': 'cherry tomatoes',
  'frischen tomaten': 'fresh tomatoes',
  'tomaten': 'tomatoes',
  'zwiebeln': 'onions',
  'knoblauch': 'garlic',
  'zucchini': 'courgettes',
  'gemüse': 'vegetables',
  'salat': 'salad',
  'rucola': 'rocket',
  'frischen kräutern': 'fresh herbs',
  'kräutern': 'herbs',
  'kräuter': 'herbs',
  'rosmarin': 'rosemary',
  'thymian': 'thyme',
  'basilikum': 'basil',
  'salbei': 'sage',
  'minze': 'mint',
  'peperoni': 'chilli peppers',
  'paprika': 'bell pepper',
  'chili': 'chilli',
  'curry': 'curry',
  'senf': 'mustard',
  'olivenöl': 'olive oil',
  'schinken': 'ham',
  'salami': 'salami',
  'speck': 'bacon',
  'käse': 'cheese',
  'sahne': 'cream',
  'butter': 'butter',
  'ei': 'egg',
  'kartoffeln': 'potatoes',
  'reis': 'rice',
  'brot': 'bread',
  'zitronensaft': 'lemon juice',
  'holunderblüte': 'elderflower',
  'zitrone': 'lemon',
  'orange': 'orange',
  'alkoholfreie': 'non-alcoholic',
  'alkoholfrei': 'non-alcoholic',
  'hausgemachter': 'homemade',
  'hausgemachte': 'homemade',
  'hausgemacht': 'homemade',
  'besonders an warmen tagen beliebt': 'especially popular on warm days',
  'leicht fruchtig': 'lightly fruity',
  'spritzig': 'sparkling',
  'pikant': 'spicy',
  'herb': 'dry',
  'frischem': 'fresh',
  'frischen': 'fresh',
  'frische': 'fresh',
  'frischer': 'fresh',
  'kleine portion': 'small portion',
  'portion': 'portion',
  'vegetarisch': 'vegetarian',

  /* --- Getränke --- */
  'hausgemachte limonade': 'homemade lemonade',
  'limonade': 'lemonade',
  'apfelschorle': 'apple spritzer',
  'weinschorle': 'wine spritzer',
  'mineralwasser': 'sparkling mineral water',
  'stilles wasser': 'still water',
  'wasser': 'water',
  'rotwein': 'red wine',
  'weißwein': 'white wine',
  'roséwein': 'rosé wine',
  'hauswein': 'house wine',
  'wein': 'wine',
  'bier vom fass': 'draught beer',
  'bier': 'beer',
  'saft': 'juice',
  'apfelsaft': 'apple juice',
  'orangensaft': 'orange juice',
  'traubensaft': 'grape juice',
  'kaffee': 'coffee',
  'tee': 'tea',
  'flasche': 'bottle',
  'glas': 'glass',
  'trocken': 'dry',
  'halbtrocken': 'medium dry',
  'lieblich': 'sweet',
  'eisgekühlt': 'ice-cold',
  'frisch gepresst': 'freshly squeezed',


  /* --- Ergänzung: Wortschatz aus der Speciale-Karte und aus Küche und Gemüsefach --- */
  'austern': 'oysters',
  'auster': 'oyster',
  'garnelen': 'prawns',
  'garnele': 'prawn',
  'roten gambas': 'red prawns',
  'rote gambas': 'red prawns',
  'roten garnelen': 'red prawns',
  'vongole-sud': 'clam broth',
  'doradenfilet': 'sea bream fillet',
  'venusmuscheln': 'clams',
  'miesmuscheln': 'mussels',
  'jakobsmuscheln': 'scallops',
  'kaper': 'caper',
  'kapern': 'capers',
  'auf eis': 'on ice',
  'eis': 'ice cream',
  'gegrillte': 'grilled',
  'gegrillten': 'grilled',
  'gegrillter': 'grilled',
  'gerösteter': 'roasted',
  'gerösteten': 'roasted',
  'geröstete': 'roasted',
  'geröstet': 'roasted',
  'halbgetrockneten': 'semi-dried',
  'halbgetrocknete': 'semi-dried',
  'getrockneten': 'dried',
  'getrocknete': 'dried',
  'gebratenes': 'fried',
  'gebratener': 'fried',
  'frittierte': 'deep-fried',
  'frittierten': 'deep-fried',
  'frittiert': 'deep-fried',
  'gedünstet': 'steamed',
  'gedünstete': 'steamed',
  'gedünsteten': 'steamed',
  'geschmort': 'braised',
  'geschmorte': 'braised',
  'geschmorten': 'braised',
  'gekocht': 'cooked',
  'gekochte': 'cooked',
  'gekochten': 'cooked',
  'gebacken': 'baked',
  'gebackene': 'baked',
  'gebackenen': 'baked',
  'überbackene': 'gratinated',
  'überbackenen': 'gratinated',
  'gefüllte': 'stuffed',
  'gefüllten': 'stuffed',
  'gefüllter': 'stuffed',
  'mariniert': 'marinated',
  'marinierte': 'marinated',
  'marinierten': 'marinated',
  'geräucherte': 'smoked',
  'geräucherten': 'smoked',
  'geräuchert': 'smoked',
  'karamellisiert': 'caramelised',
  'karamellisierte': 'caramelised',
  'karamellisierten': 'caramelised',
  'gereiftem': 'aged',
  'gereifter': 'aged',
  'gereifte': 'aged',
  'gereiften': 'aged',
  'gesalzenen': 'salted',
  'gesalzene': 'salted',
  'gesalzener': 'salted',
  'serviert': 'served',
  'knuspriges': 'crispy',
  'knusprige': 'crispy',
  'knusprigen': 'crispy',
  'knuspriger': 'crispy',
  'goldbraunes': 'golden-brown',
  'goldbraune': 'golden-brown',
  'goldbraunen': 'golden-brown',
  'perfekt': 'perfect',
  'saftig': 'juicy',
  'saftige': 'juicy',
  'saftigen': 'juicy',
  'zart': 'tender',
  'zarte': 'tender',
  'zarten': 'tender',
  'cremig': 'creamy',
  'cremige': 'creamy',
  'cremigen': 'creamy',
  'cremiger': 'creamy',
  'würzige': 'aromatic',
  'würzigen': 'aromatic',
  'würzig': 'aromatic',
  'milde': 'mild',
  'mild': 'mild',
  'scharfe': 'hot',
  'scharfen': 'hot',
  'scharf': 'hot',
  'pikante': 'spicy',
  'pikanten': 'spicy',
  'pikanter': 'spicy',
  'feinen': 'fine',
  'feine': 'fine',
  'feiner': 'fine',
  'hausgemachten': 'homemade',
  'hausgemachtes': 'homemade',
  'selbstgemachte': 'homemade',
  'selbstgemachten': 'homemade',
  'frisches': 'fresh',
  'saisonal': 'seasonal',
  'saisonale': 'seasonal',
  'saisonalen': 'seasonal',
  'saisonbedingt': 'seasonal',
  'der saison': 'of the season',
  'verschiedene': 'various',
  'verschiedenen': 'various',
  'gemischte': 'mixed',
  'gemischten': 'mixed',
  'gemischter': 'mixed',
  'kleine': 'small',
  'kleinen': 'small',
  'kleiner': 'small',
  'große': 'large',
  'großen': 'large',
  'großer': 'large',
  'roten': 'red',
  'rote': 'red',
  'roter': 'red',
  'rotem': 'red',
  'grünen': 'green',
  'grüne': 'green',
  'weißen': 'white',
  'weiße': 'white',
  'schwarzen': 'black',
  'schwarze': 'black',
  'ganze': 'whole',
  'ganzen': 'whole',
  'ganz': 'whole',
  'halbe': 'half',
  'halb': 'half',
  'stücke': 'pieces',
  'stücken': 'pieces',
  'portionen': 'portions',
  'scheiben': 'slices',
  'scheibe': 'slice',
  'monate': 'months',
  'monaten': 'months',
  'burratacreme': 'burrata cream',
  'auberginencreme': 'aubergine cream',
  'roastbeef': 'roast beef',
  'tomaten-confit': 'tomato confit',
  'tomate': 'tomato',
  'zitronen-risotto': 'lemon risotto',
  'weißwein-salbei-soße': 'white wine and sage sauce',
  'rotweinsoße': 'red wine sauce',
  'sud': 'broth',
  'zwiebelbrot': 'onion bread',
  'petersilie': 'parsley',
  'petersilienvinaigrette': 'parsley vinaigrette',
  'crunch von der kaper': 'caper crunch',
  'haselnüssen': 'hazelnuts',
  'haselnüsse': 'hazelnuts',
  'walnüssen': 'walnuts',
  'walnüsse': 'walnuts',
  'mandeln': 'almonds',
  'pistazien': 'pistachios',
  'entenbrust': 'duck breast',
  'ente': 'duck',
  'gans': 'goose',
  'kaninchen': 'rabbit',
  'hirsch': 'venison',
  'reh': 'venison',
  'lammkarree': 'rack of lamb',
  'lamm': 'lamb',
  'kalbsleber': 'calf liver',
  'kalb': 'veal',
  'rindfleisch': 'beef',
  'schweinefleisch': 'pork',
  'rinderschmorbraten': 'braised beef',
  'steinpilzen': 'porcini',
  'steinpilz': 'porcini',
  'trüffel': 'truffle',
  'trüffeln': 'truffles',
  'pilzen': 'mushrooms',
  'pilze': 'mushrooms',
  'pilz': 'mushroom',
  'kürbissuppe': 'pumpkin soup',
  'kürbis': 'pumpkin',
  'kartoffelpüree': 'mashed potatoes',
  'süßkartoffel': 'sweet potato',
  'kartoffel': 'potato',
  'rote bete': 'beetroot',
  'karotten': 'carrots',
  'möhren': 'carrots',
  'sellerie': 'celery',
  'lauch': 'leek',
  'fenchel': 'fennel',
  'blumenkohl': 'cauliflower',
  'bohnen': 'beans',
  'linsen': 'lentils',
  'kichererbsen': 'chickpeas',
  'feigen': 'figs',
  'weintrauben': 'grapes',
  'trauben': 'grapes',
  'äpfeln': 'apples',
  'apfel': 'apple',
  'birnen': 'pears',
  'pflaumen': 'plums',
  'kirschen': 'cherries',
  'himbeeren': 'raspberries',
  'erdbeeren': 'strawberries',
  'blaubeeren': 'blueberries',
  'beeren': 'berries',
  'granatapfel': 'pomegranate',
  'honig': 'honey',
  'zucker': 'sugar',
  'salz': 'salt',
  'pfeffer': 'pepper',
  'essig': 'vinegar',
  'balsamico': 'balsamic vinegar',
  'öl': 'oil',
  'milch': 'milk',
  'joghurt': 'yoghurt',
  'schlagsahne': 'whipped cream',
  'eigelb': 'egg yolk',
  'eier': 'eggs',
  'mehl': 'flour',
  'nüssen': 'nuts',
  'nüsse': 'nuts',
  'zitronenscheiben': 'lemon slices',
  'zitronenbutter': 'lemon butter',
  'knoblauchbutter': 'garlic butter',
  'kräuterbutter': 'herb butter',
  'zum': 'with',
  'zur': 'with',
  'an': 'on',
  'über': 'over',
  'unter': 'under',
  'bei': 'at',
  'auch': 'also',
  'nur': 'only',
  'als': 'as',
  'wahlweise': 'optionally',
  'auf wunsch': 'on request',

  /* --- Ergänzung: Hinweise, Ansprache, Karten --- */
  'werfen sie gerne einen blick auf': 'feel free to take a look at',
  'werfen sie einen blick auf': 'take a look at',
  'werfen sie gerne einen blick in': 'feel free to take a look at',
  'sprechen sie uns gerne an': 'please ask our staff',
  'fragen sie uns gerne': 'feel free to ask us',
  'bitte beachten sie auch': 'please also note',
  'bitte beachten sie': 'please note',
  'wir empfehlen': 'we recommend',
  'empfehlen wir': 'we recommend',
  'unsere': 'our',
  'unseren': 'our',
  'unserem': 'our',
  'unserer': 'our',
  'unser': 'our',
  'unseres': 'our',
  'euer': 'your',
  'ihre': 'your',
  'ihren': 'your',
  'ihrem': 'your',
  'ihnen': 'you',
  'sie': 'you',
  'wir': 'we',
  'uns': 'us',
  'dessertkarte': 'dessert menu',
  'speisekarte': 'menu',
  'getränkekarte': 'drinks menu',
  'weinkarte': 'wine list',
  'mittagskarte': 'lunch menu',
  'tageskarte': 'daily menu',
  'saisonkarte': 'seasonal menu',
  'süße': 'sweet',
  'süßen': 'sweet',
  'süßes': 'sweet',
  'süßer': 'sweet',
  'süß': 'sweet',
  'highlights': 'highlights',
  'highlight': 'highlight',
  'gerne': 'gladly',
  'blick': 'look',
  'werfen': 'take',
  'leckere': 'delicious',
  'leckeren': 'delicious',
  'leckerer': 'delicious',
  'lecker': 'delicious',
  'köstliche': 'delicious',
  'köstlichen': 'delicious',
  'besondere': 'special',
  'besonderen': 'special',
  'besonders': 'especially',
  'neu': 'new',
  'neue': 'new',
  'neuen': 'new',
  'jede woche': 'every week',
  'jeden tag': 'every day',
  'täglich': 'daily',
  'heute': 'today',
  'nur heute': 'today only',
  'solange der vorrat reicht': 'while stocks last',
  'bitte': 'please',
  'danke': 'thank you',
  'willkommen': 'welcome',
  'genießen': 'enjoy',
  'genießen sie': 'enjoy',
  'probieren sie': 'try',
  'probieren': 'try',
  'empfehlung': 'recommendation',
  'empfehlungen': 'recommendations',
  'hinweis': 'note',
  'hinweise': 'notes',
  'allergene': 'allergens',
  'allergien': 'allergies',
  'unverträglichkeiten': 'intolerances',
  'fragen': 'questions',
  'frage': 'question',
  'nachfrage': 'request',
  'anfrage': 'request',

  'fragen zu': 'questions about',
  'nicht gültig an feiertagen': 'not valid on public holidays',
  'nicht gültig': 'not valid',
  'gültig': 'valid',
  'feiertagen': 'public holidays',
  'feiertage': 'public holidays',
  'liefer- und außer-haus-service': 'delivery and takeaway service',
  'lieferservice': 'delivery service',
  'außer-haus-service': 'takeaway service',
  'außer-haus-verkauf': 'takeaway',
  'einen': 'a',
  'dessertkarte für süße highlights': 'dessert menu for sweet highlights',
  'süsse': 'sweet',

  'laktosefrei': 'lactose-free',
  'frisch': 'fresh',
  'zusammengestellt': 'put together',
  'zusammengestellte': 'put together',
  'zusammengestellten': 'put together',
  'für sie': 'for you',

  /* --- Bindewörter ganz zum Schluss --- */
  'sowie': 'as well as',
  'dazu': 'with',
  'oder': 'or',
  'und': 'and',
  'mit': 'with',
  'ohne': 'without',
  'auf': 'on',
  'aus': 'from',
  'vom': 'of the',
  'von': 'from',
  'einer': 'a',
  'einem': 'a',
  'eine': 'a',
  'ein': 'a',
  'der': 'the',
  'die': 'the',
  'das': 'the',
  'den': 'the',
  'dem': 'the',
  'in': 'in',
  'im': 'in the',
  'nach': 'in',
  'für': 'for',
  'je': 'per',
  'stück': 'piece',
};

/* Alles einmal nach Länge sortieren: „frischen champignons“ muss vor
   „champignons“ und „frischen“ drankommen. */
const LISTE = Object.keys(BEGRIFFE).sort((a,b)=> b.length - a.length)
  .map(k => ({ such: new RegExp('(^|[^\\p{L}])(' + esc(k) + ')(?![\\p{L}])', 'giu'),
               rein: BEGRIFFE[k] }));

const KLEIN = ['butter','curry','ketchup','mayonnaise','dressing','broccoli','salami','mustard'];
function esc(s){ return s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'); }

/* Großschreibung am Satzanfang übernehmen */
function wieVorlage(vorlage, text){
  if(!vorlage || !text) return text;
  const ersterBuchstabe = vorlage.match(/\p{L}/u);
  if(ersterBuchstabe && ersterBuchstabe[0] === ersterBuchstabe[0].toUpperCase())
    return text.charAt(0).toUpperCase() + text.slice(1);
  return text;
}

/* Übersetzt einen Namen oder eine Beschreibung.
   Italienische Namen und alles Unbekannte bleiben unverändert stehen. */
function uebersetzen(text){
  const roh = String(text||'').trim();
  if(!roh) return '';

  const ganz = SAETZE[roh.toLowerCase().replace(/[.!]+$/,'')];
  if(ganz) return wieVorlage(roh, ganz) + (/[.!]$/.test(roh) ? roh.slice(-1) : '');

  let aus = roh;
  for(const {such, rein} of LISTE){
    aus = aus.replace(such, (treffer, vorher, wort, stelle)=>{
      /* Gleiches Wort in beiden Sprachen (Curry, Mozzarella, Camembert …):
         dann bleibt die Schreibweise des Gastgebers stehen. */
      const satzAnfang = stelle === 0 || /[.!?]\s+$/.test(aus.slice(0, stelle+vorher.length));
      if(rein.toLowerCase() === wort.toLowerCase()){
        /* Gewöhnliche Hauptwörter (Butter, Curry …) schreibt das Englische klein;
           Käse- und Gerichtnamen (Mozzarella, Calamari …) behalten ihre Großschreibung. */
        return vorher + (!satzAnfang && KLEIN.includes(wort.toLowerCase()) ? wort.toLowerCase() : wort);
      }
      /* Im Deutschen ist jedes Hauptwort groß — im Englischen nur das
         erste Wort des Satzes. Sonst steht da „with Chanterelles“. */
      return vorher + (satzAnfang ? wieVorlage(wort, rein) : rein);
    });
  }
  return aus;
}

/* Für die festen Beschriftungen der Karte */
function begriff(schluessel){
  return SAETZE[String(schluessel||'').toLowerCase()] || schluessel;
}

return { uebersetzen, begriff, SAETZE, BEGRIFFE };
})();

if(typeof window !== 'undefined') window.Woerterbuch = Woerterbuch;
if(typeof module !== 'undefined') module.exports = Woerterbuch;
